pipeline {
  environment {
    registry = "awassink/docker-test"
    registryCredential = "dockerhub"
  }
  agent {
    kubernetes {
      //cloud 'kubernetes'
      label 'mypod'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:1.11
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
"""
    }
  }

  tools {
    // Install the Maven version configured as "M3" and add it to the path.
    maven "M3"
  }

  stages {
    stage('Build application') {
      steps {
        // Get some code from a GitHub repository
        git 'https://github.com/awassink/music-demo-app.git'

        // Run Maven on a Unix agent.
        sh "cd backend; mvn clean package"
      }

      post {
        // If Maven was able to run the tests, even if some of the test
        // failed, record the test results and archive the jar file.
        success {
          archiveArtifacts 'backend/target/*.war'
        }
      }
    }
    stage('Building image') {
      steps{
        container('docker') {
          script {
            sh "cd backend"
            docker.build registry + ":$BUILD_NUMBER"
          }
        }
      }
    }
  }
}