pipeline {
  environment {
    registry = "awassink/docker-test"
    registryCredential = "dockerhub"
  }
  agent {
    kubernetes {
      //cloud 'kubernetes'
      label 'mypod'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
"""
    }
  }

  tools {
    // Install the Maven version configured as "M3" and add it to the path.
    maven "M3"
  }

  stages {
    stage('Build application') {
      steps {
        // Get some code from a GitHub repository
        git 'https://github.com/awassink/music-demo-app.git'

        // Run Maven on a Unix agent.
        sh "cd backend; mvn clean package"
      }

      post {
        // If Maven was able to run the tests, even if some of the test
        // failed, record the test results and archive the jar file.
        success {
          archiveArtifacts 'backend/target/*.war'
        }
      }
    }
    stage('Building image') {
      steps{
        container('kaniko') {
          dir ("backend") {
            sh "/kaniko/executor -f `pwd`/Dockerfile -c `pwd`"
          }
        }
      }
    }
  }
}